# src/Mc/ApiBundle/Resources/config/serializer/Entity.Price.yml
Mc\ApiBundle\Entity\Price:
    exclusion_policy: none
    properties:
        id:
            groups: ['place', 'price']
        type:
            groups: ['place', 'price']
        value:
            groups: ['place', 'price']
        place:
            groups: ['price']