<?php

namespace Mc\ApiBundle\Repository;

/**
 * PlaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaceRepository extends \Doctrine\ORM\EntityRepository
{

    public function myFindAll($limit = "", $offset = "", $sort = null)
    {

        $qb = $this
            ->createQueryBuilder('p');
        if ($offset != "") {
            $qb->setFirstResult($offset);
        }

        if ($limit != "") {
            $qb->setMaxResults($limit);
        }

        if (in_array($sort, ['asc', 'desc'])) {
            $qb->orderBy('p.name', $sort);
        }

        return $qb->getQuery()->getResult();

    }
}
